javaoperatorsdk:
  reconcilers:
    customservicereconciler:
      retry:
        maxAttempts: 3

fint:
  client:
    password: ''
    username: ''
    base-url: https://idp.felleskomponent.no
    registration-id: fint
  operator:
    test-mode: false
    nam:
      oauth-client:
        name-prefix: k8s-op_

spring:
  application:
    name: namerator
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://idp.felleskomponent.no/nidp/oauth/nam
      client:
        provider:
          fint-idp:
            token-uri: https://idp.felleskomponent.no/nidp/oauth/nam/token
        registration:
          fint:
            authorization-grant-type: password
            client-id:
            client-secret:
            provider: fint-idp
            scope: urn:netiq.com:nam:scope:oauth:registration:full

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
