kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: namerator
  labels:
    app.kubernetes.io/name: namerator
    app.kubernetes.io/instance: flais-namerator
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: GA
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: fintlabs-application-infrastructure-services
    fintlabs.no/team: flais
subjects:
- kind: ServiceAccount
  name: namerator
  namespace: operators
roleRef:
  kind: ClusterRole
  name: namerator
  apiGroup: rbac.authorization.k8s.io