apiVersion: v1
kind: ServiceAccount
metadata:
  name: namerator
  labels:
    app.kubernetes.io/name: fint-namerator
    app.kubernetes.io/instance: namerator
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: GA
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: fintlabs-application-infrastructure-services
    fintlabs.no/team: flais