apiVersion: onepassword.com/v1
kind: OnePasswordItem
metadata:
  name: namerator
  labels:
    app.kubernetes.io/name: namerator
    app.kubernetes.io/instance: flais-namerator
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: GA
    app.kubernetes.io/component: operator
    app.kubernetes.io/part-of: fintlabs-application-infrastructure-services
    fintlabs.no/team: flais
spec:
  itemPath: "vaults/aks-alpha-vault/items/namerator"